### ISSUE TITLE
Text and item colors being affected by Optifine lightmaps incorrectly

### ISSUE THREAD

**Issue by HEROshineMC** [kvverti/colormatic#91] opened 2022-03-25 06:00 UTC
Hi! Basically what the title says. Being able to customize text color is cool, but I don't think using simple Optifine lightmaps should affect text color since they don't with Optifine, so all Optifine packs need to be edited to be the same on Colormatic. I assume this is unintended behavior?

For these examples I made a lightmap to color everything red using the Optifine lightmap image method, which is the only resource pack I'm using. Everything I mention is for things that are affected by the lightmap when using Colormatic that shouldn't be. As far as I know there's nothing that *isn't* colored by the lightmap that *should* be, but if I find anything like that I'll let ya know :)

### Text:
Colormatic:
![2022-03-24_22 30 40](https://user-images.githubusercontent.com/60427702/160060386-e586d2d8-d393-42c7-98cc-af7dfcac0b12.png)
Optifine:
![2022-03-24_22 43 21](https://user-images.githubusercontent.com/60427702/160061708-47c79a00-05f6-451f-87ce-71d18709d3d4.png)

Shouldn't be affected by lightmap but are:
- Chat
- XP level
- Title
- Subtitle
- Actionbar
- Item name
- Boss bar title
- Any overlayed info like F3

Of course the blocks and my player model (which includes my hand / the item in my hand) are affected by lightmap properly.

### Here's the text from menus being colored by the lightmap when they shouldn't:
Colormatic:
![2022-03-24_22 23 34](https://user-images.githubusercontent.com/60427702/160060607-72a92682-a8f3-4451-9358-a191c717ae55.png)
Optifine:
![2022-03-24_22 43 37](https://user-images.githubusercontent.com/60427702/160061776-c3afdf63-7286-4639-bd98-11820074984f.png)

Shouldn't be affected by lightmap but are:
- Menu text

### Here's all items in GUIs being colored by the lightmap when they shouldn't:
Colormatic:
![2022-03-24_22 24 11](https://user-images.githubusercontent.com/60427702/160060714-3430fa58-76c6-415a-8fc7-bad1fcde3ecf.png)
Optifine:
![2022-03-24_22 43 42](https://user-images.githubusercontent.com/60427702/160061811-b661234a-bc3b-4d9d-98f2-af660f3df9f1.png)

Shouldn't be affected by the lightmap but are:
- GUI items
- Inventory player model

Of course items as entities, blocks that are placed, and items that are shown on the player model are properly colored, but items in GUIs are not meant to be.

---

I'm not sure if this is intended or not, but if it is then maybe an option could be included to alter how Optifine lightmaps are processed by Colormatic, with an option to make it identical to Optifine?

Fantastic mod by the way, I'm finally ditching Optifine and you're part of the reason why that's even possible. ❤️ 😄 I know you just got the MC 1.18.2 version out so I hope I'm not overworking you here! 😅

Thanks, HERO

**Comment by ChloeDawn** [comment] 2022-03-29 08:40
Duplicate of #6

**Closed** 2022-04-27 01:41 UTC
Labels: duplicate
