### ISSUE TITLE
Crash On Loading World (NullPointerException)

### ISSUE THREAD

**Issue by TheLegitStick** [kvverti/colormatic#54] opened 2021-09-17 09:55 UTC
Here is my full crash report, including PC specs, mod list, etc...
https://bytebin.lucko.me/gqMNwZN6vM

As stated, the game only crashes upon loading into a world.

**Comment by kvverti** [comment] 2021-09-17 18:23
Duplicate of #51

**Comment by kvverti** [comment] 2021-09-17 18:23
Wait wrong issue

**Comment by kvverti** [comment] 2021-09-19 21:34
Do any of the mods you have installed add overworld biomes?

**Closed** 2021-09-22 17:09 UTC
Labels: pending release
