### ISSUE TITLE
Colormatic is crashing with Create and REI

### ISSUE THREAD

**Issue by efffauw** [kvverti/colormatic#95] opened 2022-05-21 08:16 UTC
Log: https://gist.github.com/efffauw/c372b158cd63e5f81100afb3b9d2a3e1
How to reproduce: https://www.youtube.com/watch?v=oNONcANfCic

**Comment by kvverti** [comment] 2022-05-21 16:51
Duplicate of #94

**Closed by kvverti** 2022-05-21 16:51 UTC
Labels: duplicate
