### ISSUE TITLE
Custom Colors not working with Patrix Resourcepack

### ISSUE THREAD

**Issue by SirPytan** [kvverti/colormatic#56] opened 2021-09-22 12:55 UTC
I use Iris and Sodium and Complementary Shaders, as well as some other mods.
The problem is that dyeable blocks like wool, carpet, terracotta, and so on are not receiving their right colors, they all stay white when placed.

These blocks are the issue: https://ibb.co/ZMh4vWQ

Here an example from my world: https://ibb.co/Sr716SL

**Comment by kvverti** [comment] 2021-09-22 17:09
Colormatic does not apply custom biome colors to blocks whose models are not tint-capable. This is a limitation of Colormatic, currently; and requires hooking into the renderer, which I would like to avoid for mod compatibility's sake.

Duplicate of #17

**Closed by kvverti** 2021-09-22 17:09 UTC

**Comment by SirPytan** [comment] 2021-09-22 22:48
@kvverti What do you mean with not tint-capable, you mean tinted by the world, not wool, and so on? Who do you think then is responsible for adding this functionality? Iris or a shader developer? Because it needs to use the data from the resource pack, so it needs to be available or accessible somehow for a shader then, right?

**Comment by SirPytan** [comment] 2021-09-22 22:53
@kvverti And can you maybe update your readme file here on GitHub as well as stating clearly on the Curseforge page, that Custom colors for those types of blocks are not supported currently, and depending on you also will not be added/supported anytime soon.
